export const GET_USER_LIST_PROCESS = 'GET_USER_LIST_PROCESS';
export const GET_USER_LIST_RESULT = 'GET_USER_LIST_RESULT';

export const GET_FILTER_PROCESS = 'GET_FILTER_PROCESS';
export const GET_FILTER_RESULT = 'GET_FILTER_RESULT';
