export const GET_TRACK_LIST_PROCESS = 'GET_TRACK_LIST_PROCESS';
export const GET_TRACK_LIST_RESULT = 'GET_TRACK_LIST_RESULT';

export const GET_ARTIST_LIST_PROCESS = 'GET_ARTIST_LIST_PROCESS';
export const GET_ARTIST_LIST_RESULT = 'GET_ARTIST_LIST_RESULT';

export const GET_SEARCH_TRACK_LIST_PROCESS = 'GET_SEARCH_TRACK_LIST_PROCESS';
export const GET_SEARCH_TRACK_LIST_RESULT = 'GET_SEARCH_TRACK_LIST_RESULT';
export const GET_SEARCH_ARTIST_LIST_PROCESS = 'GET_SEARCH_ARTIST_LIST_PROCESS';
export const GET_SEARCH_ARTIST_LIST_RESULT = 'GET_SEARCH_ARTIST_LIST_RESULT';
